"""
Generiere 6 Creatives für Landau Personas
via Frontend (Gradio) - MANUELLE ANLEITUNG
"""

print("="*80)
print("LANDAU PERSONAS - 6 CREATIVES GENERIERUNG")
print("="*80)
print()
print("Da die Backend-API ein Problem mit google.generativeai hat,")
print("nutze bitte das Gradio Frontend zur Generierung:")
print()
print("1. Browser öffnen: http://localhost:7870")
print("2. Tab '⚡ Quick' auswählen")
print("3. Folgende 6 Anfragen eingeben:")
print()
print("="*80)
print("PERSONA 1: Die erfahrene Touren-PFK (PROFESSIONELL)")
print("="*80)
print("Stellentitel: Pflegefachkraft (m/w/d)")
print("Firmenname: Ökumenische Sozialstation Landau in der Pfalz e. V.")
print("Standort: Landau in der Pfalz")
print("Website: -")
print("→ Generieren klicken")
print()
print("="*80)
print("PERSONA 1: Die erfahrene Touren-PFK (KÜNSTLERISCH)")
print("="*80)
print("(Wiederholen mit gleichem Input)")
print()
print("="*80)
print("PERSONA 2: Die Wiedereinsteigerin (PROFESSIONELL)")
print("="*80)
print("Stellentitel: Pflegefachkraft Wiedereinstieg (m/w/d)")
print("Firmenname: Ökumenische Sozialstation Landau in der Pfalz e. V.")
print("Standort: Landau in der Pfalz")
print("Website: -")
print("→ Generieren klicken")
print()
print("="*80)
print("PERSONA 2: Die Wiedereinsteigerin (KÜNSTLERISCH)")
print("="*80)
print("(Wiederholen mit gleichem Input)")
print()
print("="*80)
print("PERSONA 3: Die junge Generalistin (PROFESSIONELL)")
print("="*80)
print("Stellentitel: Pflegefachkraft mit Entwicklungsperspektive (m/w/d)")
print("Firmenname: Ökumenische Sozialstation Landau in der Pfalz e. V.")
print("Standort: Landau in der Pfalz")
print("Website: -")
print("→ Generieren klicken")
print()
print("="*80)
print("PERSONA 3: Die junge Generalistin (KÜNSTLERISCH)")
print("="*80)
print("(Wiederholen mit gleichem Input)")
print()
print("="*80)
print()
print("HINWEIS: Die Auto-Quick Pipeline generiert automatisch passende")
print("         Headlines und Sublines basierend auf dem Stellentitel.")
print()
print("ALTERNATIVE: Backend-Fix für google.genai durchführen")
print("="*80)
